### PR TITLE
Fix interaction with other non-LEDControl plugins that use LEDs

### PR DESCRIPTION
**Pull request by cdisselkoen**
Prior to this commit, using SolidColor with other plugins such as Kaleidoscope-LED-ActiveModColor that have LED effects but aren't LED "modes", was buggy.  Specifically, the extra LED effects would not be turned "off" properly and revert to the SolidColor.  This means, e.g., the Shift key would stay highlighted forever after a single use, until the LED mode was switched.  

This could be considered either SolidColor's problem or ActiveModColor's, but I think it is more robust to fix it here.  This also makes SolidColor work exactly like the existing behavior of the LED-Off mode.

### CODE REVIEW

**Comment by cdisselkoen** [comment]
Actually, we could make LED-Off just a special case of SolidColor with the color CRGB(0,0,0).  Might save a few bytes of code, as they could share implementation.  To do that, though, we either need to make LED-Off require the SolidColor header (ick), or just merge the SolidColor functionality into the LEDControl plugin.  LEDControl already provides more than one public class (i.e., LEDControl and LEDOff), so there's precedent.  I can create a PR against LEDControl if this is desired.

**Comment by obra** [comment]
Fixing it in ActiveModColor feels cleaner to me.

My major concern about this change is that it fixes the problem by adding a bunch of work on every cycle, rather than just at setup time. This will have a measurable impact on our event loop speed. One of the nice things about the solid color LED effects is that they're lower overhead.

(At some point, I do want to figure out how to take advantage of the model 01's attiny opcode for 'set all leds to this color', which will further reduce this.)

**Comment by cdisselkoen** [comment]
In that case should we change LED-Off to work like the current behavior of SolidColor?  I.e., set the LEDs off only once rather than every update().  

We can still consider making LED-Off a special case of SolidColor if you like.

**Comment by algernon** [comment]
I'd like to have a different proposal: keyboardio/Kaleidoscope-LEDControl#10. That would - in my opinion - fix the issue in a better way.

**Comment by algernon** [comment]
I think keyboardio/Kalediscope-LEDControl#11 & related PRs address the problem better, by using the new `LEDControl.refreshAt()` in `Kaleidoscope-LED-ActiveModColor`. 

As @obra said, setting LEDs each cycle is very, very costly in terms of speed, so the less we do that, the better. Even if it is a no-op, it still has significant cost that could be avoided. The `.refreshAt()` method you suggested in keyboardio/Kaleidoscope-LEDControl#9 works wonderfully in this case, and is a lot more efficient at accomplishing pretty much the same thing.

For this reason, I'm closing this PR, it is superseded by fixes being done elsewhere. Thank you for reporting the issue, and even more so, for coming up with the proper fix (`refreshAt`)!

**Pull request closed without merging**
